# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xCtIgCt8-2JVkrWxSvjV3Pmv67BMptzv
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(color_codes=True)


import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv("Iris.csv")
df.head()

# Membuat Scatter Plot dari fitur SepalLengthCm dan SepalWidthCm
df.plot(kind="scatter", x="SepalLengthCm", y="SepalWidthCm")

# Atau dengan Library Seaborn
sns.jointplot(x="SepalLengthCm", y="SepalWidthCm", data=df, size=5)

# Salah satu informasi yang hilang dalam plot diatas adalah jenis tanaman (Species)
# Gunakan FacetGrid Seaborng untuk mewarnai sebaran Species
sns.FacetGrid(df, hue="Species", palette="husl", size=5) \
.map(plt.scatter, "SepalLengthCm", "SepalWidthCm") \
.add_legend()

# 3 plot dengan jenis Palette atau warna yang berbeda
sns.FacetGrid(df, hue="Species", palette="hls", size=5) \
.map(plt.scatter, "SepalLengthCm", "SepalWidthCm") \
.add_legend()

sns.FacetGrid(df, hue="Species", palette="Set2", size=5) \
.map(plt.scatter, "SepalLengthCm", "SepalWidthCm") \
.add_legend()

sns.FacetGrid(df, hue="Species", palette="cubehelix", size=5) \
.map(plt.scatter, "SepalLengthCm", "SepalWidthCm") \
.add_legend()

# pairplot
# Dibawah ini ada kolom Id yang dihapus karena tidak memiliki korelasi dengan variabel lain
sns.pairplot(df.drop("Id", axis=1), hue="Species", palette="husl", size=3)