# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d14CIGMCkZXiiXO4KqeVTNRPmcNe2Rn5
"""

import pandas as pd

#Load dataset Iris Unclean
df = pd.read_csv('iris_unclean.csv')

# Tampilkan dataset
df

# Hitung jumlah nilai null pada dataset
df.isna().sum()

# Cari nilai mean dari SepalLengthCm
df['SepalLengthCm'].mean()

# Mengganti missing value dengan mean(), kemudian masukkan ke variabel
dfDataBaru = df['SepalLengthCm'].fillna(df['SepalLengthCm'].mean())

# Cek Data
dfDataBaru

# Gabung Data Baru menjadi DataFrame
df2 = pd.DataFrame({'SepalLengthCm': dfDataBaru, 'SepalWidthCm': df['SepalWidthCm'],
                    'PetalLengthCm': df['PetalLengthCm'], 'PetalWidthCm': df['PetalWidthCm'],
                    'Species':df['Species']})
df2

# Cek jumlah baris dan kolom
df2.info()

# Hitung jumlah nilai null pada DataFrame baru
df2.isna().sum()