# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RsASwSZLPMYySwAvjcd7sN05A_1jr0v_
"""

import pandas as pd

# Panggil file (Iris.csv). Lalu tampilkan 5 baris awal dataset dengan function head()
df = pd.read_csv("Iris.csv")
df.head()

# Tampilkan tipe data dari kolom yang ada pada dataset menggunakan dtypes
df.dtypes

# Hitung ukuran (jumlah baris pada kolom) pada dataset
df.info()

# Tampilkan data untuk "Id" dan kolom "Species" dalam bentuk dataframe
df[["Id","Species"]]

# Tampilkan data baris indeks ke-0 (nol) sampai dengan indeks ke-9 (sembilan)
df.iloc[:10]

# Tampilkan data hanya kolom "Id" dan kolom "Species", dan yang ditampilkan adalah data indeks ke-11 (sebelas)
# Sampai dengan indeks ke-15 (limabelas)
df[["Id","Species"]].iloc[11:16]

# Tampilkan data 8 baris pertama
df.head(8)

# Tampilkan data 3 baris terakhir
df.tail(3)

# Hitung data mean dari dataset
df.mean()

# Hitung nilai mean untuk kolom PetalLengthCm
df["PetalLengthCm"].mean()

# Cari nilai minimal untuk kolom SepalWidthCm
df["SepalWidthCm"].min()

# Hitung frekuensi pada kolom Species dengan menggunakan metode value_counts()
df["Species"].value_counts()

# Tampilkan perhitungan frekuesi pada kolom Species menggunakan value_counts() dalam bentuk dataframe
dfValueCountsSpecies = df["Species"].value_counts().rename_axis('Species Value Counts').reset_index(name='counts')
dfValueCountsSpecies

# Hitung frekuensi pada kolom PetalLengthCm dengan menggunakan value_counts() dalam bentuk dataframe
dfValuePetalLengthCm = df["PetalLengthCm"].value_counts().rename_axis('PetalLengthCm Value Counts').reset_index(name='counts')
dfValuePetalLengthCm

