# -*- coding: utf-8 -*-
"""Visualisasi Data : Matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pq6pXDydYxKajIhIqewRzsJ3dWELlrBL

# **Plot Garis**
Merupakan representasi berupa garis yang menghubungkan antar posisi koordinat data. Cara membuatnya sebagai berikut.
"""

# matplotlib adalah Library python yang digunakan untuk menampilkan grafik
from matplotlib import pyplot as plt
x = [4,6,10,13,16,20,22,24,26,28,30]
y = [100,120,160,180,210,240,270,300,320,330,350]
plt.plot(x,y)
plt.show()

"""# **Menambah Label Title**"""

from matplotlib import pyplot as plt
sumbux = [4,6,10,13,16,20,22,24,26,28,30]
sumbuy = [100,120,160,180,210,240,270,300,320,330,350]
plt.plot(sumbux,sumbuy)

#menambah label dan title
plt.title('Kenaikan Subscriber Berdasarkan Hari')
plt.xlabel('Hari')
plt.xlabel('Jumlah Subscriber')

plt.show()

"""# **Plot Garis Multiline**"""

from matplotlib import pyplot as plt

hari = [4,6,10,13,16,20,22,24,26,28,30]

#sumbu y pertama
young_lex = [100,120,160,180,210,240,270,300,320,330,350]
plt.plot(hari,young_lex)

#sumbu y kedua
atta = [120,140,200,230,260,280,290,320,360,380,300]
plt.plot(hari,atta)

#menambah label dan title
plt.title('Kenaikan Subscriber Berdasarkan Hari')
plt.xlabel('Hari')
plt.xlabel('Jumlah Subscriber')

plt.show()

"""# **Legend**"""

from matplotlib import pyplot as plt

hari = [4,6,10,13,16,20,22,24,26,28,30]
young_lex = [100,120,160,180,210,240,270,300,320,330,350]
plt.plot(hari,young_lex)

atta = [120,140,200,230,260,280,290,320,360,380,400]
plt.plot(hari,atta)

plt.title('Kenaikan Subscriber Berdasarkan Hari')
plt.xlabel('Hari')
plt.ylabel('Jumlah Subscriber')

#Legend, digunakan untuk memberikan info masing-masing plot
plt.legend(['Young Lex','Atta Halilintar'])

plt.show()

"""# **Color, LineStyle, Marker**"""

from matplotlib import pyplot as plt

hari = [4,6,10,13,16,20,22,24,26,28,30]
young_lex = [100,120,160,180,210,240,270,300,320,330,350]

#color, untuk warna garis
#lifestyle, untuk jenis garis
#-.
#--
#marker, penanda untuk pertemuan sumbu x dan sumbu y
#p, pentangon
#D, diamond

plt.plot(hari,young_lex, color='#444444', linestyle='--', marker='D')

atta = [120,140,200,230,260,280,290,320,360,380,400]
plt.plot(hari,atta, color='#5A7D9A', marker='.')

plt.title('Kenaikan Subscriber Berdasarkan Hari')
plt.xlabel('Hari')
plt.ylabel('Jumlah Subscriber')

plt.legend(['Young Lex','Atta Halilintar'])

plt.show()

"""# **Linewidth**"""

from matplotlib import pyplot as plt

hari = [4,6,10,13,16,20,22,24,26,28,30]
young_lex = [100,120,160,180,210,240,270,300,320,330,350]
plt.plot(hari,young_lex, color='#444444', linestyle='--', marker='o')

#Linewidth, untuk menebalkan garis
atta = [120,140,200,230,260,280,290,320,360,380,400]
plt.plot(hari,atta, color='#5A7D9A', marker='D', linewidth='3')

plt.title('Kenaikan Subscriber Berdasarkan Hari')
plt.xlabel('Hari')
plt.ylabel('Jumlah Subscriber')

plt.legend(['Young Lex','Atta Halilintar'])

plt.show()

"""# **Grid**"""

from matplotlib import pyplot as plt

hari = [4,6,10,13,16,20,22,24,26,28,30]
young_lex = [100,120,160,180,210,240,270,300,320,330,350]
plt.plot(hari,young_lex, color='#444444', linestyle='--', marker='o')

atta = [120,140,200,230,260,280,290,320,360,380,400]
plt.plot(hari,atta, color='#5A7D9A', marker='D', linewidth='3')

plt.title('Kenaikan Subscriber Berdasarkan Hari')
plt.xlabel('Hari')
plt.ylabel('Jumlah Subscriber')

plt.legend(['Young Lex','Atta Halilintar'])

#grid, untuk menampilkan layout grid (Susunan Vertikal dan Horizontal)
plt.grid(True)

plt.show()

"""# **Menggunakan Style (fivethirtyeight) Gambar**"""

from matplotlib import pyplot as plt

#meggunakan style fivethirtyeight
plt.style.use('fivethirtyeight')
#plt.style.use('ggplot')

hari = [4,6,10,13,16,20,22,24,26,28,30]
young_lex = [100,120,160,180,210,240,270,300,320,330,350]
plt.plot(hari,young_lex, color='#444444', linestyle='--', marker='o')

atta = [120,140,200,230,260,280,290,320,360,380,400]
plt.plot(hari,atta, color='#5A7D9A', marker='D', linewidth='3')

plt.title('Kenaikan Subscriber Berdasarkan Hari')
plt.xlabel('Hari')
plt.ylabel('Jumlah Subscriber')

plt.legend(['Young Lex','Atta Halilintar'])
plt.grid(True)

#tight_layout(), digunakan untuk menyesuaikan plot, label, title didalam area gambar
plt.tight_layout()
plt.show()

"""# **Menggunakan Style ggplot**"""

from matplotlib import pyplot as plt

#menggunakan style ggplot
plt.style.use('ggplot')

hari = [4,6,10,13,16,20,22,24,26,28,30]
young_lex = [100,120,160,180,210,240,270,300,320,330,350]
plt.plot(hari,young_lex, color='#444444', linestyle='--', marker='o')

atta = [120,140,200,230,260,280,290,320,360,380,400]
plt.plot(hari,atta, color='#5A7D9A', marker='D', linewidth='3')

plt.title('Kenaikan Subscriber Berdasarkan Hari')
plt.xlabel('Hari')
plt.ylabel('Jumlah Subscriber')

plt.legend(['Young Lex','Atta Halilintar'])
plt.grid(True)
plt.tight_layout()
plt.show()

"""# **Plot Garis dan Bar**

Ketika menggunakan plot bar, **tidak boleh** menggunakan **linestyle** dan **marker**. Ini hanya berlaku untuk plot garis

"""

from matplotlib import pyplot as plt

plt.style.use('fivethirtyeight')

hari = [4,6,10,13,16,20,22,24,26,28,30]
young_lex = [100,120,160,180,210,240,270,300,320,330,350]
plt.bar(hari,young_lex, color='#444444', label='Young Lex')

atta = [120,140,200,230,260,280,290,320,360,380,400]
plt.plot(hari,atta, color='#5A7D9A', label='Atta Halilintar')

plt.title('Kenaikan Subscriber Berdasarkan Hari')
plt.xlabel('Hari')
plt.ylabel('Jumlah Subscriber')

plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""# **Plot Bar**

Ketika menggunakan plot bar. Jika ada 2 data (2 sumbu y), maka dataset yang bilangannya paling tinggi harus diletakkan diatas. Sehingga pada grafik akan tampil dibelakang bar lain.
"""

from matplotlib import pyplot as plt

plt.style.use('fivethirtyeight')

hari = [4,6,10,13,16,20,22,24,26,28,30]

atta = [120,140,200,230,260,280,290,320,360,380,400]
plt.bar(hari,atta, color='#E5AE38', label='Atta Halilintar')

young_lex = [100,120,160,180,210,240,270,300,320,330,350]
plt.bar(hari,young_lex, color='#008FD5', label='Young Lex')

plt.title('Kenaikan Subscriber Berdasarkan Hari')
plt.xlabel('Hari')
plt.ylabel('Jumlah Subscriber')

plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""# **Plot Bar** (side by side)"""

from matplotlib import pyplot as plt
import numpy as np

plt.style.use('fivethirtyeight')

hari = [4,6,10,13,16,20,22,24,26,28,30]

# menghitung posisi
# np dari modul numpy untuk mengelola data array
# len untuk menghitung jumlah karakter atau array/list
x_indeks = np.arange(len(hari))

# lebar bar adalah 0.35 per unit bar
lebar_bar = 0.35
print(len(hari))
print(x_indeks)
print(x_indeks-lebar_bar)

atta = [120,140,200,230,260,280,290,320,360,380,400]
plt.bar(x_indeks-lebar_bar, atta, width=lebar_bar, color='#E5AE38', label='Atta Halilintar')

young_lex = [100,120,160,180,210,240,270,300,320,330,350]
plt.bar(x_indeks, young_lex, width=lebar_bar, color='#008FD5', label='Young Lex')

plt.title('Kenaikan Subscriber Berdasarkan Hari')
plt.xlabel('Hari')
plt.ylabel('Jumlah Subscriber')

#xticks, digunakan untuk menentukan posisi dan meng-set label sesuai data list
plt.xticks(ticks=x_indeks, label=hari)

plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""# **Matplotlib - Import Data CSV**
Dibawah ini adalah praktikum cara menampilkan plot dengan menggunakan file CSV

# **Dengan Plot Bar**

# **1. Tampilkan Key dan Value**
"""

from matplotlib import pyplot as plt
import numpy as np
import csv

plt.style.use('fivethirtyeight')

with open('cloth_data.csv') as csv_file:
  csv_reader = csv.DictReader(csv_file)

  #menampilkan key dan value 
  row = next(csv_reader)
  print(row)

"""# **2. Tampilkan Value Berdasarkan Nama Key**"""

from matplotlib import pyplot as plt
import numpy as np
import csv

plt.style.use('fivethirtyeight')

with open('cloth_data.csv') as csv_file:
  csv_reader = csv.DictReader(csv_file)

  # Hanya menampilkan value berdasarkan nama "key" 
  row = next(csv_reader)
  print(row['height'].split(';'))

"""# **3. Hitung semua Height**"""

from matplotlib import pyplot as plt
import numpy as np
import csv
from collections import Counter

plt.style.use('fivethirtyeight')

with open('cloth_data.csv') as csv_file:
  csv_reader = csv.DictReader(csv_file)

  # Hitung semua height
  hitung = Counter()

  for row in csv_reader:
    hitung.update(row['height'].split(';'))

    print(hitung)

"""# **4. Tampilkan Jumlah Pengguna Teratas dan Batas Tertentu**"""

from matplotlib import pyplot as plt
import numpy as np
import csv
from collections import Counter

plt.style.use('fivethirtyeight')

with open('cloth_data.csv') as csv_file:
  csv_reader = csv.DictReader(csv_file)

  hitung = Counter()

  for row in csv_reader:
    hitung.update(row['height'].split(';'))

    print(hitung.most_common(15))

"""# **5. Pisahkan Value Bahasa dan Jumlah Pengguna ke Dalam Masing - Masing List **"""

from matplotlib import pyplot as plt
import numpy as np
import csv
from collections import Counter

plt.style.use('fivethirtyeight')

with open('cloth_data.csv') as csv_file:
  csv_reader = csv.DictReader(csv_file)

  hitung = Counter()

  for row in csv_reader:
    hitung.update(row['height'].split(';'))

  height = []
  age = []

  for item in hitung.most_common(15):
    height.append(item[0])
    age.append(item[1])
print(height)
print(age)

from matplotlib import pyplot as plt
import numpy as np
import csv
from collections import Counter

plt.style.use('fivethirtyeight')

with open('cloth_data.csv') as csv_file:
  csv_reader = csv.DictReader(csv_file)

  hitung = Counter()

  for row in csv_reader:
    hitung.update(row['height'].split(';'))

  height = []
  age = []

  for item in hitung.most_common(15):
    height.append(item[0])
    age.append(item[1])

    plt.bar(height,age)

    plt.title('Clothing Data')
    plt.xlabel('Banyaknya')
    plt.ylabel('Jumlahnya')
    plt.show()

"""# **8. Reverse (Tampilkan Data dari Banyak ke Sedikit)**"""

from matplotlib import pyplot as plt
import numpy as np
import csv
from collections import Counter

plt.style.use('fivethirtyeight')

with open('cloth_data.csv') as csv_file:
  csv_reader = csv.DictReader(csv_file)

  hitung = Counter()

  for row in csv_reader:
    hitung.update(row['height'].split(';'))

  height = []
  age = []

  for item in hitung.most_common(15):
    height.append(item[0])
    age.append(item[1])

    height.reverse()
    age.reverse()

    plt.barh(height,age)

    plt.title('Clothing Data')
    plt.ylabel('Jumlahnya')
    plt.xlabel('Banyaknya')
    plt.show()

"""# **Plot Pie Chart**"""

from matplotlib import pyplot as plt

plt.style.use('fivethirtyeight')

#slices, digunakan untuk membagi pie menjadi beberapa bagian
slices = [60,40]
plt.pie(slices)

plt.title('Contoh Pie Chart')
plt.tight_layout()
plt.show()

"""# **2. Label**"""

from matplotlib import pyplot as plt

plt.style.use('fivethirtyeight')

#slices, digunakan untuk membagi pie menjadi beberapa bagian
slices = [60,40]

#label untuk menampilkan label perbagian
label = ['Enam Puluh','Empat Puluh']
plt.pie(slices, labels=label)

plt.title('Contoh Pie Chart')
plt.tight_layout()
plt.show()

"""# **3. Wedgeprops**"""

from matplotlib import pyplot as plt

plt.style.use("fivethirtyeight")

#slices, digunakan untuk membagi pie menjadi beberapa bagian
slices = [60,40]

#label untuk menampilkan label perbagian
label = ['Enam Puluh','Empat Puluh']

#wedgeprops, digunakan untuk membuat garis pinggir/border pie
plt.pie(slices, labels=label, wedgeprops={'edgecolor':'black'})

plt.title("Contoh Pie Chart")
plt.tight_layout()
plt.show()

"""# **4. Colors**"""

from matplotlib import pyplot as plt

plt.style.use("fivethirtyeight")

#slices, digunakan untuk membagi pie menjadi beberapa bagian
slices = [60,40]

#label untuk menampilkan label perbagian
label = ['Enam Puluh','Empat Puluh']

#color untuk merubah warna pie
warna = ['#E5AE37','#6D904F']

#wedgeprops, digunakan untuk membuat garis pinggir/border pie
plt.pie(slices, labels=label, colors=warna, wedgeprops={'edgecolor':'black'})

plt.title("Contoh Pie Chart")
plt.tight_layout()
plt.show()

"""# **5. Explode**"""

from matplotlib import pyplot as plt

plt.style.use("fivethirtyeight")

slices = [59219, 55466, 47544, 36443]
label =  ['weight','age','height','size']
warna = ['#E5AE37','#6D904F']
explode = [0,0,0,0.1]

#explode artinya fraksi atau pecahan pie
plt.pie(slices, labels=label, explode=explode, wedgeprops={'edgecolor':'black'})

plt.title("Contoh Pie Chart")
plt.tight_layout()
plt.show()

"""# **6. Shadow**"""

from matplotlib import pyplot as plt

plt.style.use("fivethirtyeight")

slices = [59219, 55466, 47544, 36443]
label =  ['weight','age','height','size']
warna = ['#E5AE37','#6D904F']
explode = [0,0,0,0.1]

#shadow=True untuk menampilkan bayangan
plt.pie(slices, labels=label, explode=explode, shadow=True, wedgeprops={'edgecolor':'black'})

plt.title("Contoh Pie Chart")
plt.tight_layout()
plt.show()

"""# **7. Startangle**"""

from matplotlib import pyplot as plt

plt.style.use("fivethirtyeight")

slices = [59219, 55466, 47544, 36443]
label =  ['weight','age','height','size']
warna = ['#E5AE37','#6D904F']
explode = [0,0,0,0.1]

#angle digunakan untuk memutar derajat pie
plt.pie(slices, labels=label, explode=explode, shadow=True, startangle=90, wedgeprops={'edgecolor':'black'})

plt.title("Contoh Pie Chart")
plt.tight_layout()
plt.show()

"""# **8. Autopct**"""

from matplotlib import pyplot as plt

plt.style.use("fivethirtyeight")

slices = [59219, 55466, 47544, 36443]
label =  ['weight','age','height','size']
warna = ['#E5AE37','#6D904F']
explode = [0,0,0,0.1]

#autopct untuk menampilkan bagian persen dari pie
#%f artinya menampilkan bilangan float. Harus diawali %
#%0.1f menampilkan bilangan float dengan 1 angka dibelakang koma
#%0.1f%% menampilkan simbol % itu sendiri dan ditutup dengan %
plt.pie(slices, labels=label, explode=explode, shadow=True, startangle=90, autopct='%0.1f%%', wedgeprops={'edgecolor':'black'})

plt.title("Contoh Pie Chart")
plt.tight_layout()
plt.show()